### ISSUE TITLE
24h clock not working

### ISSUE THREAD

**Issue by crankc** [jooooscha/Olauncher#32]
The clock displayed by Olauncher on home screen is 12h, even with system set up as 24h (status bar and lock screen display it correctly). Tested on Android 12 phone, Android 12 tablet, and Android 11 phone. All devices run LineageOS and have their region set to Finland, and to use the 24h format. Changing these system settings doesn't seem to make a difference. <- some did, see below.

The date is also in English (displaying May) instead of what the system language equivalent is. Seems like the app isn't getting locale info correctly?

Olauncher actually showed 24h on one device for a moment, but reverted to 12h on reboot. No idea why, or what i did to make that happen. I cannot turn it to 24h format again. Ideas?

**Comment by crankc** [comment]
Disabling automatic time format in Android settings changes it to 24h format, but the weekday and month remain in English, apparently due to English being set as the app language. Could the day/month strings be pulled from device localization, instead of app settings? I'm sure i've seen some apps do that.

**Comment by jooooscha** [comment]
I cannot confirm the 12H/24H bug. I have my phone set to 24H and if I change it now to 12H in the system settings, Olauncher correctly switches to 12H. I would need more (specific) information on when this bug occurs.

It was a specific request that the language should be editable in the settings. If I have time, I could add an "automatic" settings.

**Comment by crankc** [comment]
This is pretty weird. When i boot the device(s), Olauncher shows the day and month in English. After some time, 30min to few hours, it has changed to Finnish. I can't say what causes it to switch, but it has now occurred on all three of my devices.

You are correct about 12/24h: when i manually selected 24h, Olauncher switched to 24h. However, Olauncher doesn't seem to get the correct value (24h) when "Automatic time format" is selected. Android decides the time format based on timezone, i think, when it's set to automatic.

An automatic setting might solve this problem, if the launcher then gets the correct format immediately when the app is started. Thanks!

**Comment by jooooscha** [comment]
#33 adds a option to load the locale settings from the system settings. I will merge that later and release it with the next version.

From a quick view, the 24H/12H clock things seems to come from a library. Without putting more time into it, I have little control over that.

For your spooky language change. I cannot see what caused that. Maybe try to find some sort of pattern. Otherwise, I don't see how I could help you with that.

**Comment by crankc** [comment]
Great! I'll test it when it hits F-Droid, and report back if it works.

I'll keep an eye on the day/month language changes, but i restarted Olauncher (no need to reboot the whole device, restarting the app is enough to reset the language) on all devices last night, and this morning they've all changed from English to Finnish on their own, so it only needs to be idle for x amount of time. I've never seen any other app behave this way. Let's hope the automatic setting will help with this.

**Comment by Ilithy** [comment]
I use myself (I'm French, living in France) the 24H cycle, and Olauncher displays the time correctly on all my devices (including my main one under GrapheneOS without GSF/GPS/GMS).

@crankc  Are you still affected by this bug?

This issue seems ready to be closed 🙂
Thanks

**Comment by jooooscha** [comment]
It is?

I remember looking into this but did not find the cause immediately so I did other things first.

However, I think the cause might be in a library, so there is only so much I can do to that. If the merge of  #30 is through (and proofs to be stable), I might start to rewrite more parts of the app in jetpack compose. Then I could also exchange that library.

**Comment by Ilithy** [comment]
> It is?

I think so, personally. I don't know if @crankc is still dealing with this bug (seems specific on LineageOS), but with no response from that, hopefully this has been fixed (or it was a temporary bug)

I don't face this bug on any of my devices (several of which are exempt from google/play service/play store services), and since no other user does, so I figured that until this another user confirms the presence of this bug, this issue may be considered resolved, am I wrong?
(because that's just my opinion ;-))

**Comment by jooooscha** [comment]
Closing this. Please add any further discusison in #144

**Comment by jhpgcj** [comment]
I'm using version 1.2.10, from F-Droid, and non-rooted Android 11.

I confirm this also happens to me. Not the language change, though. Text from the calendar is always in my native language, even if the clock is wrong. Everything else is the same: the clock seems to randomly change between 12/24h, and changing system settings to only use 24h-format "fixes" the issue.

**Comment by Npa972** [comment]
No problem for me (cheap xiaomi 9C, cleaned with ADB, android 11). I do not use the stock clock but this one : https://github.com/qw123wh/new-clock

**Comment by cenktaskin** [comment]
I can tell the issue persists on v1.3.2, with stock Android 13,on google pixel 6a. Confirmed it on another device of a friend with pixel experience custom rom, on pixel 3a. 

According to the discussion here I had played with "interface language" on app settings and "Use locale format" on android settings. First switching the app interface language setting to "System" from "English" made it work then it got back to way it was. Playing with Android settings didn't change anything. I can tell it works somehow but there should be some sort of bug.

**Comment by jooooscha** [comment]
Thanks for reporting again.

This is still mostly code from the original Olauncher. I should finally replace the clock with a better implementation.

I try to do it for one of the next releases.

**Comment by RokeJulianLockhart** [comment]
**https://github.com/OlauncherCF/OlauncherCF/issues/32#issuecomment-1317063228**

> This is still mostly code from the original Olauncher. I should finally replace the clock with a better implementation.

@jooooscha, why not fix it upstream instead? Additionally, does it now adhere to the system preference?
